import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="flex items-center justify-between p-4 border-b bg-gradient-to-r from-purple-600 to-violet-700 text-white dark:from-purple-800 dark:to-violet-900">
          <Link href="/" className="font-bold text-lg hover:underline">
            Math Site
          </Link>
          <nav className="flex gap-4">
            <Link href="/login" className="hover:underline">
              로그인
            </Link>
            <Link href="/signup" className="hover:underline">
              회원가입
            </Link>
            <Link href="/problems" className="hover:underline">
              문제
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
